url: https://riddhi927.github.io
baseurl: /home

# Site settings
title: Riddhi Pathak
email: rp3726@nyu.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Instagram
    url: https://www.instagram.com/riddhipathak27/
  - title: LinkedIn 
    url: https://www.linkedin.com/in/riddhi-pathak-rp3726/
  - title: github
    url: http://github.com/riddhi927

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
